### ISSUE TITLE
QGIS 3.38 error when running python script in a console.

### ISSUE THREAD

**Issue by tsmcgrath** [opengisch/qgis-conda-builder#22]
QGIS-3.38.2-MacOSX-arm64.pkg is throwing an error when I try to run a script that was previously working previously using the first ARM native install (3.34? 3.36?). It immediately throws this error which seems to mean it cannot find the code to execute. Not 100% sure as I'm not very good at debugging the deeper errors in the libraries called.
Error:
`exec(compile(Path('/var/folders/s_/v06y7rf94sj26yw8qlb7r5740000gn/T/tmpk8i_0mct').read_text(), 'Untitled-0', 'exec'))
Traceback (most recent call last):
  File "/Applications/QGIS-3.38.app/Contents/lib/python3.11/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "Untitled-0", line 30, in <module>
IndexError: list index out of range`

When I go back to try 3.36 it is now a crashing error. I'll file a separate issue on that as it is different. See #21

**Comment by tsmcgrath** [comment]
Here's a clue. I restarted QGIS 3.38.2 and am successfully running a very similar script (geology instead of canopy cover maps). But there was this message:
`Plugin qfieldsync: This plugin is disabled because it previously crashed QGIS.`

So, I'm going to uninstall that and see if it fixes the problem.

**Comment by tsmcgrath** [comment]
That did not fix the problem. Bottom line is that it is definitely in my script or data that causes the crash. Because virtually identical scripts and data do not crash. But, the fact that it crashes with no crash report is a bug on your side.

**Comment by tsmcgrath** [comment]
It turns out the QGIS dataset had invalid geometry. So, this issue can be closed. Tracking the crashing issue in #21.
